# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events...
  # ...but only for the pure-z3 and master branches
  push:
    branches: [ pure-z3, master]
  pull_request:
    branches: [ pure-z3, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT: ArchC

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  build:
    name: "Test - Pharo"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Z3
        run: sudo apt-get install libz3-4 libz3-dev

      - name: Download Pharo
        run: |
          sudo apt-get install curl
          curl https://get.pharo.org/64/80+vm | bash

      - name: Download PDLs
        run: bash -x ./get-pdls.sh

      - name: Build
        run: |
          ./pharo Pharo.image save $PROJECT
          ./pharo $PROJECT.image metacello install tonel://./src BaselineOf$PROJECT

      - name: Test
        run: |
          export ARCHC_PDL_DIR=$(pwd)/pdl/
          ./pharo $PROJECT.image eval "AcProcessorDescriptions baseDirectory"
          ./pharo $PROJECT.image test --fail-on-failure "$PROJECT.*Test.*"
