# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events...
  # ...but only for the pure-z3 and master branches
  push:
    branches: [ pure-z3, master]
  pull_request:
    branches: [ pure-z3, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT: ArchC

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  test:
    name: "${{matrix.dialect}}, ${{matrix.os}}"
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.group }} == 'alternative-bitvector'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        dialect: [ pharo, stx ]
        group: [ default, alternative-bitvector ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Z3
        run: sudo apt-get install libz3-4 libz3-dev

      - name: Fetch commits so that Iceberg doesn't crash
        run: git fetch --unshallow

      - name: Build
        run: |
          make GROUP=${{matrix.group}} -C ${{matrix.dialect}}

      - name: Test
        run: |
          export ARCHC_PDL_DIR=$(pwd)/pdl/
          make GROUP=${{matrix.group}} -C ${{matrix.dialect}} test
